version: '3'

services:

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"

  prometheus:
    image: prom/prometheus
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ../monitoring/alerts.rules.yml:/etc/prometheus/alerts.rules.yml
    ports:
      - "9090:9090"
    depends_on:
      - node-exporter

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager

    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--web.external-url=http://35.154.171.179:9093'

    volumes:
    - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml

    env_file:
      - ../.env

    ports:
      - "9093:9093"